Trap build failure and grep error log

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -25,7 +25,8 @@ jobs:
         gradle-version: '8.5'
         
     - name: Build with Gradle
-      run: gradle assembleDebug --stacktrace
+      run: |
+        gradle assembleDebug --stacktrace > build.log 2>&1 || { grep -A 50 "FAILURE: " build.log; exit 1; }
 
     - name: Upload APK
       uses: actions/upload-artifact@v4
